action_access_key.go
action_destination.go
action_destination_test.go
action_transaction.go
action_xpub.go
import.go
interface.go
model_destinations_test.go
model_transactions_test.go
model_xpubs.go
model_xpubs_test.go

instead of as a function argument

Changed signature of action methods to use WithMetadatas in options

---

errors.go
model_paymails.go
model_paymails_test.go

This allows a user to segregate identity keys from payment keys. Internal chain can keep a constant identity key that can be rotated, external chain will update everytime a payment request is made

Add support for internal paymail keys for identity usage

---

action_paymails.go
errors.go
interface.go

Added GetPaymailAddress action

---

model_draft_transactions.go
model_draft_transactions_test.go
utils/scripts.go

Fixed transaction signing

---

action_transaction_test.go
bux_test.go
model_destinations.go
model_destinations_test.go
model_xpubs_test.go
utils/keys.go
utils/keys_test.go

This should shave off considerably when creating new draft transactions, especially with multiple change addresses

Added some tests and benchmarks, changed setAddress on draft transaction to only derive what is needed

---

action_transaction.go
chainstate/monitor_client.go
client_internal.go
client_options.go
definitions.go
interface.go
model_destinations.go
monitor.go
monitor_event_handler.go
tasks.go

- Rudimentary multi-server support using Cachestore and heartbeat
- Supports a `LockID` and `heartbeat` time
- Runs a task every X seconds looking for an active monitor
- Record monitor tx is now an internal method (not public anymore)

Feature: Multi-server improvements for destination Monitoring

---

action_transaction.go
interface.go
utils/destination_types.go
utils/destination_types_test.go

Also sneaked in a small STAS test (unknowingly)

Added RecordRawTransaction action

---

monitor_event_handler.go

Fixed block sync channel closing go routine when closed

---

monitor_event_handler.go

Added missing client to publish handlers in monitor

---

model_sync_transactions.go
tasks.go

Hi all, could you please review this carefully as this solves some pain points we are having in TonicPow, but it does change the broadcasting quite a bit.

Added grouping of transactions per xpub when broadcasting and run in parallel

---

model_transactions.go

BeforeCreate lifecycle function is called twice when synchronising with blockchain and getting incoming transaction.
First time it is in [action_transaction.go:191](https://github.com/BuxOrg/bux/blob/master/action_transaction.go#L191) where it is called with such a comment:
`run before create to see whether xpub_in_ids or xpub_out_ids is set`
And second time it is called during save as a part of standard lifecycle in [model_save.go:33](https://github.com/BuxOrg/bux/blob/master/model_save.go#L33)

fix: quickfix for duplication of UTXO in incoming transactions

---

action_paymails.go

Related links:
---
GitHub Issue: https://github.com/BuxOrg/bux/issues/295
Description:
---
- Checking if paymail exists before creating new one

fix: check if paymail already exist before creating new one

---

model_transactions.go

Description
-----
- Removed transaction metadata resetting. This change is necessary if we want to save information in metadata but we want it to readable by both users (sender and receiver). Until now If we send data in metadata by RecordTransaction method it will be saved but in xpub_metada with sender pub_id as key.

feat: remove resetting transaction metadata before save

---

action_paymails.go
model_draft_transactions.go
model_transaction_config.go
model_transaction_config_test.go

Fixes empty paymail in outgoing transactions.
Before:
After:
Handchash was used as the recipient for test transactions.

fix: fixes empty sender's paymail

---

chainstate/broadcast.go
chainstate/broadcast_providers.go
chainstate/broadcast_test.go
chainstate/broadcast_utils.go
chainstate/chainstate.go
chainstate/mock_minercraft.go
chainstate/mock_nownodes_test.go
chainstate/mock_whatsonchain_test.go

change broadcasting logic:
- run broadcasting to providers in separate go routine
- register fastest successful broadcast on the synchronization channel
- response to end-client as soon as the fastest provider records the broadcast

Perf speed up tx broadcasting

---

paymail_service_provider.go

Each incoming paymail transaction is considered obviously external(DRAFT_ID == NIL), which is not correct, since the case bux to bux transactions is not taken into account.

fix(BUX-136): internal paymail transaction bug

---

client_options.go
definitions.go
model_transaction_config.go
model_transactions.go
tasks.go

Description
------------
- Added new task for transaction model which check if there are transactions with height 0 and then create request to miners to synchronize transactions.
When transaction have height 0?
If users is using method `AdminRecordTransaction` in go or js buxclient the transactions is the only created object (for example for recording STAS tokens in BUX). Without SyncTransaction it can not be synchronized. Added task provide a way to update information about this transactions

Feat: add new transaction task

---

model_draft_transactions.go

Such txs don’t contain “money to send”, but only OpReturn. So the validation should be disabled for such cases

feat(BUX-157): disabling of a dust limit validation for txs with OpReturn

---

definitions.go
model_transactions.go
tasks.go

Description
-------
- Changed number of transactions which are checked in task
- Updated db query conditions because MongoDB do not have default values like PostgreSQL (example block_height = 0) we need to get also headers with block_height = nil

chore: update check transaction task

---

action_utxo.go
interface.go

Creation of a draft transaction will mark UTXOs as reserved, and those UTXOs can't be used for another transaction.
If a draft transaction was created, but the "record transaction" process failed, UTXOs will still be reserved and can't be used for another payment.
A mechanism for unreserving UTXOs should be added for such cases.

fix: add unreserve utxos action

---

chainstate/broadcast.go
chainstate/broadcast_providers.go
chainstate/broadcast_test.go

Context: 
1. As I understood from previous discussions we should focus on providing support for common/standarized API especially Arc (and for now still support for mApi).
2. Just as an extension to that, we have similar broadcasting support for Now Nodes, should we remove it also?
Answers:
1. Agreed
2. Agreed, we are specifically building on this software to avoid relying on a node. NowNodes is counter to this mission.

feat(BUX-180): remove option to use whatsonchain and nownodes for broadcasting

---

chainstate/broadcast_test.go
chainstate/client_test.go
chainstate/transaction_test.go

*Some of the tests require running redis, so you also need to run it on your machine to get the same result.

fix(BUX-287): failed tests on local machine

---

beef_tx.go
beef_tx_bytes.go
beef_tx_sorting.go
beef_tx_sorting_test.go
model_sync_transactions.go

chore(BUX-298): refactor sync method and use go-b t structures in BEEF implementation

---

sync_tx_service.go

feat: revert BUMP calculation to sync task

---

beef_tx_test.go
model_bump.go
model_bump_test.go
model_compound_merkle_path.go
model_draft_transactions.go
model_merkle_proof.go
model_merkle_proof_test.go

feat(BUX-294): Replacing CMPSlice with BUMPPaths in DraftTransaction

---

chainstate/client.go
chainstate/client_options.go
client_options.go

During tests I found out that the `BroadcastClientApis` variable inside `chainstate` config is unused and can be removed along with the `WithBroadcastClientAPIs` function. So I did it. Without removed code, the aplication still compiles, tests pass and it works with bux-server.
If the existence of this config variable has some future/planned usage - just cancel this PR.

refactor(BUX-426): remove unused BroadcastClientApis & appropriate `With` function

---

record_tx_strategy_outgoing_tx.go
sync_tx_service.go
utils.go

perf(BUX-000): refactorize P2P - send tx to the receiver only once

---

client_options.go
definitions.go

Datastore logs all executed queries at the info level, making it difficult to read logs.
If the logger is configured to log at the info level, we set up the Datastore logger to the warning level.

Chore(bux-000) make datastore quiet

---

go.mod
go.sum

feat(BUX-437): go-resty update to prevent security issue

---

action_utxo.go
chainstate/merkle_root.go

This is a quick fix to prevent nil pointer dereferences, but a more comprehensive solution may be considered in the future.

fix(BUX-474): prevent panics in UnReserveUtxos and VerifyMerkleRoots

---

go.mod
go.sum
paymail_test.go

fix(BUX-497): update to go-paymail 12.1

---

chainstate/client.go
chainstate/client_options.go
chainstate/merkle_root.go
chainstate/merkle_root_provider.go
chainstate/merkle_root_test.go

While doing this task, I discovered that, every time a request to our Pulse service is made, a new `http.Client` is created. I've change it - so that now, only one http.Client is created during the initialization stage.
From golang documentation:
> A Client is an HTTP client. Its zero value (DefaultClient) is a usable client that uses DefaultTransport.
>
> The Client's Transport typically has internal state (cached TCP connections), so Clients should be reused instead of created as needed. Clients are safe for concurrent use by multiple goroutines.

chore(BUX-351): improve logging when requesting Pulse

---

errors.go

BUX-496: Admin record transactions

---

.github/workflows/run-tests.yml

ci(BUX-368): trigger test workflow on push to branch

---

.gitignore
action_destination.go
action_transaction.go
chainstate/broadcast_providers.go
chainstate/client.go
chainstate/client_options.go
client_options.go
cron_job_declarations.go
definitions.go
errors.go
go.mod
go.sum
interface.go
sync_tx_repository.go
sync_tx_service.go
utils/utils.go

feat(BUX-368): Arc callbacks

---

cron_job_declarations.go
sync_tx_service.go

* try broadcast outgoing transaction in cronjob if broadcast fails on recording transaction
* change cron intervals for tasks

fix: try broadcast outgoing tx again

---

action_transaction_test.go
paymail_service_provider.go
record_tx.go
record_tx_strategy_external_incoming_tx.go
record_tx_strategy_internal_incoming_tx.go
record_tx_strategy_outgoing_tx.go

BUX-480: Record Transaction
