BuxOrg/bux

- utils/utils.go
> Fix for int overflow issue

- action_transaction.go
- chainstate/mock_whatsonchain_test.go
- client.go
- client_options.go
- go.mod
- go.sum
- importer/xpub.go
- interface.go
Dependent upon: https://github.com/mrz1836/go-whatsonchain/pull/8
> Add an xpub importer library

- action_xpub.go
- import.go
- interface.go
> Update to use address history rather than bulk unspent

- action_xpub.go
- import.go
> Include used addresses for importer

- action_xpub.go
- go.mod
- go.sum
- import.go
> WIP: Move importer to bitbus

- model_transactions.go
> Added OutputValue, Status and Direction to the output of actions

- authentication.go
- authentication_internal.go
- authentication_test.go
> Updated authentication to allow non signed actions

- model_xpubs.go
> Added RemovePrivateData function to xpubs

- model_xpubs_test.go
> Added test for RemovePrivateData

- action_access_key.go
- action_destination.go
- action_transaction.go
- action_utxo.go
- authentication.go
- authentication_test.go
- errors.go
- interface.go
- model_access_keys.go
- model_destinations.go
- model_destinations_test.go
- utils/keys.go
- utils/utils.go
- utils/utils_test.go
> Updates from js client development

- definitions.go
- errors.go
- model_metadata.go
- model_paymails.go
- model_paymails_test.go
- models_test.go
> Add paymail model from bux-server

- action_destination_test.go
- action_xpub.go
- model_xpubs_test.go
> Fixed tests for client updates

- action_paymails.go
- action_paymails_test.go
- bux_suite_test.go
- interface.go
> Add paymail actions and tests

- definitions.go
> Fixed dust limit

- errors.go
- model_paymails.go
- model_paymails_test.go
- utils/utils.go
> Rework identity key management for paymails

- authentication.go
> Fixed missing request missing in authentication return on error

- action_destination.go
- action_destination_test.go
- action_transaction.go
- action_xpub.go
- action_xpub_test.go
- interface.go
- model_transactions.go
- model_transactions_test.go
- models.go
- models_internal.go
> Added update metadata function to destinations,  transactions and xpub

- chainstate/client_options.go
- chainstate/interface.go
- chainstate/monitor.go
- chainstate/processor.go
- chainstate/processor_test.go
- client.go
- client_internal.go
- monitor_event_handler.go
- utils/destination_types.go
> Add configurable options for monitoring

- chainstate/client_options.go
- chainstate/interface.go
- chainstate/monitor.go
- chainstate/processor.go
- chainstate/processor_test.go
- client.go
- client_internal.go
- monitor_event_handler.go
- utils/destination_types.go
> Revert "Add configurable options for monitoring"

- client.go
- client_internal.go
- client_options.go
- interface.go
- model_destinations.go
- model_transactions.go
- models.go
- models_internal.go
- notifications/client.go
- notifications/client_options.go
- notifications/interface.go
- notifications/notifications.go
> Bux Notifications (MVP)

- action_paymails.go
- interface.go
- model_paymails.go
> Added paymail get actions

- client_internal.go
- notifications/client.go
- notifications/client_options.go
- notifications/interface.go
- notifications/notifications.go
> Added logger to notifications options

- model_draft_transactions.go
- model_options.go
- model_utxos.go
- model_utxos_test.go
- models.go
> Added pagination to ReserveUtxos for large number of utxos in db

- action_access_key.go
- action_destination.go
- action_destination_test.go
- action_paymails.go
- action_transaction.go
- action_utxo.go
- datastore/interface.go
- datastore/models.go
- datastore/mongodb.go
- datastore/mongodb_test.go
- datastore/params.go
- datastore/params_test.go
- interface.go
- model_access_keys.go
- model_access_keys_test.go
- model_destinations.go
- model_draft_transactions.go
- model_get.go
- model_incoming_transactions.go
- model_paymails.go
- model_sync_transactions.go
- model_transactions.go
- model_transactions_test.go
- model_utxos.go
- model_utxos_test.go
- models_test.go
- monitor.go
- tasks.go
refactored all list functions to use that instead of page / pageSize
> Added datastore QueryParams

- action_blockheader.go
- chainstate/client_options.go
- chainstate/interface.go
- chainstate/monitor.go
- chainstate/monitor_client.go
- chainstate/processor.go
- chainstate/processor_test.go
- datastore/models.go
- definitions.go
- interface.go
- model_blockheaders.go
- monitor_event_handler.go
> Monitor 2.0

- monitor_event_handler.go
> Fixed possible race condition in waitgroup in monitor

- datastore/params.go
- datastore/params_test.go
> Fixed parsing query params from graphql queries into QueryParams

- model_draft_transactions.go
- model_draft_transactions_test.go
- model_transaction_config.go
> Added UseForChange option for Outputs in TransactionConfig

- action_transaction.go
- admin_actions_stats.go
- admin_interface.go
- datastore/interface.go
- datastore/models.go
- datastore/mongodb.go
- model_get.go
- model_transactions.go
- model_utxos.go
@mrz1836 This is needed to upgrade bux-server
> Model aggregate

- examples/client/custom_rates/custom_rates.go
- model_draft_transactions.go
- model_draft_transactions_test.go
- model_transaction_config.go
fixed incorrect fee in UseForChange txs
> Converted SendToAll to transaction output

- model_draft_transactions.go
- model_draft_transactions_test.go
> Set satoshis of SendToAll output to 0 before calculation of total

- errors.go
- model_draft_transactions.go
- model_draft_transactions_test.go
- model_transaction_config.go
> Fixed incorrect satoshi value in empty (SendToAll) paymail outputs

- model_sync_transactions.go
> Make sure transactions are synced in the correct order

- authentication_internal.go
> Changed http headers to be valid according to specs

- .make/go.mk
- model_xpubs.go
- models_internal.go
- paymail_service_provider.go
> Fix: increment model value not being updated on the model (hack)

- chainstate/interface.go
- chainstate/monitor.go
- client_internal.go
- examples/client/monitor/monitor.go
- monitor_event_handler.go
> Rename monitor methods and add channel cleanup

- chainstate/monitor.go
> Properly load monitored destinations and bloom filter fix

- model_transaction_config.go
- utils/outputs.go
- utils/outputs_test.go
> Fixed satoshi value of paymail outputs when more than 1 present

- action_transaction.go
- bux_suite_test.go
- chainstate/transaction.go
- model_incoming_transactions.go
- model_sync_transactions.go
- monitor.go
> Added broadcasting of incoming transaction when attempting to broadcast

- monitor_event_handler.go
> Added recover from panic when closing monitor channel on disconnect

- definitions.go
- model_sync_transactions.go
> Fixed sorting of transactions

- model_transactions.go
> Changed hex field from text to longtext in transaction model

- errors.go
- model_draft_transactions.go
- model_draft_transactions_test.go
- model_utxos.go
- model_utxos_test.go
there seems to be a case where this is possible
> Added duplicate utxo check when reserving utxos

- monitor_event_handler.go
I removed the channel from the block sync, but am not sure if it's actually working.
Maybe @galt-tr can verify that it is actually doing something on the agent side. It just blasts through the blocks in my tests.
> Changed block sync check to bool instead of channel

- action_draft_transaction.go
- action_transaction.go
- action_transaction_test.go
- action_utxo.go
- interface.go
- model_draft_transactions_test.go
- model_sync_transactions.go
- model_transactions.go
> Added revertTransaction action

- monitor_event_handler.go
> Fixed block sync not getting turned off on disconnect

- monitor_event_handler.go
> Set monitor go routines in background context

- go.mod
- go.sum
> Upgrade datastore

- action_transaction.go
- chainstate/interface.go
- chainstate/monitor.go
- monitor.go
- monitor_event_handler.go
> Tweaked recordMonitoredTransaction, fixed block header data from monitor

- model_sync_transactions.go
- model_transactions.go
> Set transaction on sync tx when creating and broadcasting initially

- action_transaction.go
- errors.go
> Return error when processing unknown transaction that will get ignored

- paymail_service_provider.go
> Do not error on receiving paymail transaction if already exists

- paymail_service_provider.go
> Added check for nil transaction returned from RecordTransaction

- monitor_event_handler.go
> Added tx id to incoming transactions that error in monitor

- monitor_event_handler.go
> Fixed error not showing when transaction could not be recorded

- action_transaction.go
Check that monitor exists before calling AllowUnknownTransactions
> check for monitor before accessing it

- cluster/memory-pub-sub.go
> fix: uninitialized map error when using MemoryPubSub

- action_transaction.go
- model_incoming_transactions.go
- model_transactions.go
- model_transactions_test.go
Fixes "utxo has already been spent" and unique constraint errors for bux to bux transactions
> fix: bux to bux transactions

- chainstate/client.go
- chainstate/client_internal.go
- chainstate/client_options.go
- chainstate/definitions.go
- chainstate/interface.go
- client_options.go
- definitions.go
- mock_chainstate_test.go
- model_draft_transactions.go
- model_draft_transactions_test.go
- model_transaction_config_test.go
- model_transactions_test.go
- tests/model_draft_transactions_test.json
New dust limit, fees from mAPI
Satoshis and fees in tests were also recalculated according to new default fee unit.
> feat: new dust limit, fees from mAPI, updated tests connected with fees

- action_transaction.go
Sometimes we face with writelock in a bux to bux tx case. Outgoing tx creates a writelock and incoming tx can't be created as outgoing tx is locking it(as both of them are part of one tx with the same tx_id).
So instead of throwing an error and forgetting about incoming tx, we'll wait for a moment when object will be unlocked and incoming tx can be created.
> fix(BUX-117): fix writelock for bux to bux txs

- action_transaction.go
- action_transaction_test.go
- model_sync_transactions.go
- model_transactions.go
- model_transactions_test.go
> feat(BUX-27): makes XPubID field public

- .make/go.mk
- definitions.go
- go.mod
- go.sum
- upgraded deps
- bumped version (v0.5.11)
- updated linter version
> chore: updates

- chainstate/broadcast_providers.go
> fix: error returning while broadcasting with go-broadcast-client

- chainstate/broadcast_test.go
- chainstate/chainstate_test.go
- chainstate/client_options_test.go
- chainstate/client_test.go
- chainstate/mock_minercraft.go
- chainstate/transaction_test.go
> Bux 222 tests with mock arc

- beef_tx.go
- beef_tx_bytes.go
- beef_tx_sorting.go
- beef_tx_sorting_test.go
- beef_tx_test.go
- model_sync_transactions.go
- paymail.go
* ffix topological sorting: use only inputs we are interested in
* hydrate transactions if needed
> fix(BUX-252):  beef econding issues

- chainstate/broadcast_providers.go
- go.mod
- go.sum
> feat(BUX-236): go-broadcast-client version update

- beef_tx.go
- beef_tx_bytes.go
- beef_tx_sorting.go
- beef_tx_sorting_test.go
> fix?: use bt structure in BEEF impl

- chainstate/client.go
- paymail.go
> chore(BUX-297): add more logs

- definitions.go
- model_bump.go
- model_merkle_proof.go
- model_merkle_proof_test.go
- model_sync_transactions.go
- model_transactions.go
> feat(BUX-293): calculate and store BUMP in DB

- beef_tx.go
- beef_tx_bytes.go
- beef_tx_test.go
- model_bump.go
- model_draft_transactions.go
> feat(BUX-295): encoding BUMP in BEEF

- beef_tx.go
- beef_tx_bytes.go
- model_bump.go
- model_bump_test.go
- model_draft_transactions.go
- model_merkle_proof.go
- model_merkle_proof_test.go
> feat(BUMP): BUMPPaths renamed to BUMPs

- chainstate/interface.go
- chainstate/merkle_root.go
- chainstate/merkle_root_provider.go
- go.mod
- go.sum
- mock_chainstate_test.go
- paymail_mocks_test.go
- paymail_service_provider.go
> feat(BUX-290): interface and methods changed to fit the new requests and responses from Pulse

- model_bump.go
- model_bump_test.go
- model_draft_transactions.go
- model_merkle_proof.go
- model_merkle_proof_test.go
> feat(BUX-250): BUMP duplicates support and bump merging refactored

- paymail_service_provider.go
> fix(BUX-250): missing paymail error

- chainstate/merkle_root_provider.go
- definitions.go
- go.mod
- go.sum
- paymail_mocks_test.go
- paymail_service_provider.go
> Feat 172 spv extended

- action_transaction.go
- client_options.go
- definitions.go
- errors.go
- interface.go
- model_draft_transactions_test.go
- model_incoming_transactions.go
- model_transaction_config.go
- model_transactions.go
- model_transactions_test.go
- monitor_event_handler.go
- record_tx_strategy_external_incoming_tx.go
- record_tx_strategy_outgoing_tx.go
- sync_tx_service.go
- tasks.go
- tx_service.go
* remove `check tx` cron job
* unify `recordMonitoredTransaction` and `RecordRawTransaction`
* move and refactorize  `action_transaction.recordTxHex()` => `tx_service.saveRawTransaction()`
> feat(BUX-358): remove check tx job

- bux_suite_mocks_test.go
- client.go
- client_internal.go
- client_options.go
- cron_job_declarations.go
- examples/client/custom_cron/custom_cron.go
- taskmanager/cron_jobs.go
- taskmanager/cron_jobs_test.go
- taskmanager/interface.go
Because of in the #502 remained unresolved important comments from @dorzepowski I'm creating this PR in which I've simplified `cronJobs` mechanism.
- The 'user' of a bux client can only adjust cron periods - instead of modifying the whole `cronJobs` configuration.
- `taskmanager.CronJobsInit` doesn't require a `target` argument. A `client` pointer is passed to tasks by a closure.
> refactor(BUX-357): cron jobs simplification

- bux_test.go
- chainstate/chainstate_test.go
- chainstate/client_options_test.go
- client_options_test.go
- client_test.go
- definitions.go
- logging/logging.go
- model_transaction_config_test.go
- paymail_test.go
- taskmanager/client_options_test.go
> Chore(BUX-000) clean tests logs

- chainstate/broadcast_providers.go
- go.mod
- go.sum
> feat(BUX-000): restore translation mechanism

- definitions.go
> chore(BUX-000): bump version to 0.13.0

- model_save.go
> fix(BUX-312): hanging transactions on database

- action_destination.go
- go.mod
- model_ids.go
- model_ids_test.go
- model_metadata.go
- model_metadata_test.go
- Remove unused methods which are using graphl lib
> feat(BUX-525): remove unused graphql methods

- action_paymails.go
- action_paymails_test.go
- errors.go
- paymail_service_provider.go
> BUX-491: Admin delete paymail

- README.md
> feat(BUX-586): mark repository as deprecated
